# Generated by Django 4.2.7 on 2024-06-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pincode',
            new_name='address_pincode',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='address_state',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_line1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
