# Generated by Django 4.2.7 on 2024-07-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
